echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
echo "sim eu fui ingenuo"
echo "Esse script poderia fazer QUALQUER coisa em menu computador"
